WIP: Add vendor app configurability
201-created/ember-inline-css pull request #4
Opened 2017-09-11 19:29 UTC by rondale-sc

2017-09-12 15:55 UTC, rondale-sc commented
@mixonic I think this is ready for review

2017-09-12 20:43 UTC, mixonic commented
@rondale-sc can you document what the intended result of this code is in the description?

2017-09-12 20:50 UTC, rondale-sc commented
@mixonic Sure thing :+1: 

Added.  🍻

2017-09-12 20:53 UTC, mixonic requested changes
Can you add a test for `vendorOnly`? It also seems preferable if there is a way to specify `vendorOnly` without coupling to the name vendor. An API such as passing the files to inlined or a regex to filter them with seems preferable.

2017-09-13 14:13 UTC, mixonic requested changes
@rondale-sc perhaps you are WIP still, I noted down a few things here.

2017-09-13 14:13 UTC, mixonic commented on tests/index-test.js
> +QUnit.module('CSSReader', function(hooks) {
I think this module name is wrong

2017-09-13 14:13 UTC, mixonic commented on tests/lib/css_injector-test.js
> +  test('when vendorOnly is specified only concats vendor.css to index.html', function(assert) {
Title is wrong, no vendorOnly

2017-09-13 14:13 UTC, mixonic commented on tests/index-test.js
> +  test('concats vendor.css / app.css into style tag inside index.html', co.wrap(function* (assert) {
I think CSSReader tests are in the other module? My impression was this module was for full integration testing.

2017-09-13 14:13 UTC, mixonic commented on tests/index-test.js
> +  test('postprocessTree vendorOnly', co.wrap(function* (assert) {
This is still testing vendorOnly

2017-09-13 15:13 UTC, mixonic approved these changes

2017-09-13 15:13 UTC, mixonic commented
This looks excellent! Thank you @rondale-sc

2017-09-13 15:13 UTC, merged